---
title: "Lab 6 Warm Up"
author: "Christina Chen"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Load data

```{r}
library(tidyverse)
library(janitor)
```

```{r}
bison <- read_csv("data/bison.csv")
clean_names(bison)
```

### 2. Dimensions and Structure of Data

```{r}
dim(bison)
```

```{r}
glimpse(bison)
```

### 3. Save Code, Sex, Weight, Year of Birth into a new object

```{r}
names(bison)
```

```{r}
bison2 <- bison %>%
  select(contains("animal"))
bison2
```

### 4. Pull Out Animals Born Between 1980 - 1990.

```{r}
bison2 %>%
  filter(between(animal_yob, 1980, 1990))
```

### 5. How Man Female vs Male Bison?

```{r}
bison3 <- bison2 %>%
  filter(between(animal_yob, 1980, 1990))

table(bison3$animal_sex)
```

### 6. Were Males or Females Larger on Average?

```{r}
bisonF <- bison3 %>%
  filter(animal_sex == "F")

mean(bisonF$animal_weight)
```

```{r}
bisonM <- bison3 %>%
  filter(animal_sex == "M")

mean(bisonM$animal_weight)
```

Males are larger on average.

